Repository IbexOmega/CrazyCanvas, pull requests merged in 2020-11, with the labels that each got.

#329 LAN servers now display the correct ping
  CrazyCanvas/Source/GUI/LobbyGUI.cpp
  CrazyCanvas/Source/GUI/SavedServerGUI.cpp
  LambdaEngine/Include/Application/API/Events/NetworkEvents.h
  LambdaEngine/Include/Game/Multiplayer/Client/ClientSystem.h
  LambdaEngine/Include/Networking/API/NetworkStatistics.h
  LambdaEngine/Include/Networking/API/UDP/INetworkDiscoveryClient.h
  LambdaEngine/Source/Game/Multiplayer/Client/ClientSystem.cpp
  LambdaEngine/Source/Networking/API/UDP/ClientNetworkDiscovery.cpp
Labels: GUI, Multiplayer, Networking

#337 Fix directional light
  Assets/Meshes/arrow_debug.glb
  Assets/RenderGraphs/RT_DEFERRED_PBR.lrg
  Assets/RenderGraphs/RT_DEFERRED_PBR_MESH.lrg
  Assets/Shaders/Helpers.glsl
  Assets/Shaders/RayTracing/Raygen.rgen
  Assets/Shaders/Shading/Shading.frag
  Assets/Shaders/ShadowMap/DirLShadowMap.frag
  Assets/World/LevelModules/directional_light_debug.glb
  Assets/World/LevelModules/module_0.glb
  Assets/World/levels.json
  CrazyCanvas/Include/States/SandboxState.h
  CrazyCanvas/Source/States/SandboxState.cpp
  CrazyCanvas/Source/World/LevelObjectCreator.cpp
  LambdaEngine/Include/Game/ECS/Components/Rendering/DirectionalLightComponent.h
  LambdaEngine/Source/Game/ECS/Systems/Rendering/RenderSystem.cpp
Labels: Rendering

#341 Extending as builder
  Assets/RenderGraphs/RT_DEFERRED_PBR.lrg
  Assets/RenderGraphs/RT_DEFERRED_PBR_MESH.lrg
  Assets/RenderGraphs/RT_DEFERRED_PBR_MESH2.lrg
  Assets/Shaders/RayTracing/RayTracingInclude.glsl
  Assets/Shaders/RayTracing/Raygen.rgen
  Assets/Shaders/Shading/Shading.frag
  CrazyCanvas/Source/RenderStages/PlayerRenderer.cpp
  CrazyCanvas/engine_config_server.json
  LambdaEngine/Include/Rendering/CustomRenderer.h
  LambdaEngine/Include/Rendering/RT/ASBuilder.h
  LambdaEngine/Include/Rendering/RenderGraph.h
  LambdaEngine/Include/Rendering/RenderGraphTypes.h
  LambdaEngine/Source/Game/ECS/Systems/Rendering/RenderSystem.cpp
  LambdaEngine/Source/Rendering/RT/ASBuilder.cpp
  LambdaEngine/Source/Rendering/RenderGraph.cpp
Labels: Fix, RenderGraph, Rendering

#342 Input action revamp
  Assets/NoesisGUI/Xaml/MainMenu2.xaml
  CrazyCanvas/Include/GUI/MainMenuGUI.h
  CrazyCanvas/Source/ECS/Systems/Player/WeaponSystem.cpp
  CrazyCanvas/Source/GUI/MainMenuGUI.cpp
  CrazyCanvas/Source/World/Player/Client/PlayerLocalSystem.cpp
  CrazyCanvas/Source/World/Player/PlayerActionSystem.cpp
  CrazyCanvas/engine_config_crazycanvas.json
  CrazyCanvas/key_bindings.json
  LambdaEngine/Include/Input/API/ActionCodes.h
  LambdaEngine/Include/Input/API/InputActionSystem.h
  LambdaEngine/Include/Input/API/InputCodes.h
  LambdaEngine/Source/Game/ECS/Systems/Audio/AudioSystem.cpp
  LambdaEngine/Source/Game/ECS/Systems/CameraSystem.cpp
  LambdaEngine/Source/Input/API/InputActionSystem.cpp
Labels: Clean Up, Fix, GUI, Game

#345 Initial version of the new Replay System
  CrazyCanvas/Include/ECS/Systems/Multiplayer/Client/ReplayBaseSystem.h
  CrazyCanvas/Include/ECS/Systems/Multiplayer/Client/ReplayManagerSystem.h
  CrazyCanvas/Include/Multiplayer/MultiplayerClient.h
  CrazyCanvas/Include/World/Player/Client/PlayerLocalSystem.h
  CrazyCanvas/Source/ECS/Systems/Multiplayer/Client/ReplayBaseSystem.cpp
  CrazyCanvas/Source/ECS/Systems/Multiplayer/Client/ReplayManagerSystem.cpp
  CrazyCanvas/Source/Multiplayer/MultiplayerClient.cpp
  CrazyCanvas/Source/World/Player/Client/PlayerLocalSystem.cpp
  LambdaEngine/Include/ECS/System.h
Labels: Game, Multiplayer

#346 Default key bindings
  LambdaEngine/Include/Input/API/InputActionSystem.h
  LambdaEngine/Source/Input/API/InputActionSystem.cpp
Labels: Clean Up, Fix

#348 Networking events fix
  CrazyCanvas/engine_config_client.json
  CrazyCanvas/engine_config_crazycanvas.json
  CrazyCanvas/engine_config_sandbox.json
  CrazyCanvas/engine_config_server.json
  LambdaEngine/Include/Engine/ConfigCodes.h
  LambdaEngine/Include/Networking/API/ClientBase.h
  LambdaEngine/Include/Networking/API/ClientRemoteBase.h
  LambdaEngine/Include/Networking/API/EProtocol.h
  LambdaEngine/Include/Networking/API/NetWorker.h
  LambdaEngine/Source/Game/Multiplayer/Client/ClientSystem.cpp
  LambdaEngine/Source/Game/Multiplayer/Server/ServerSystem.cpp
  LambdaEngine/Source/Networking/API/ClientBase.cpp
  LambdaEngine/Source/Networking/API/ClientRemoteBase.cpp
  LambdaEngine/Source/Networking/API/EProtocol.cpp
  LambdaEngine/Source/Networking/API/NetWorker.cpp
  LambdaEngine/Source/Networking/API/NetworkUtils.cpp
Labels: Fix, Networking

#354 Gui damage indicator(WIP) & Fixed Merge error
  Assets/NoesisGUI/Xaml/HUD.xaml
  Assets/NoesisGUI/Xaml/Multiplayer.xaml
  CrazyCanvas/Include/ECS/Systems/GUI/HUDSystem.h
  CrazyCanvas/Include/GUI/HUDGUI.h
  CrazyCanvas/Include/GUI/MultiplayerGUI.h
  CrazyCanvas/Include/States/MultiplayerState.h
  CrazyCanvas/Source/ECS/Systems/GUI/HUDSystem.cpp
  CrazyCanvas/Source/GUI/HUDGUI.cpp
  CrazyCanvas/Source/GUI/MainMenuGUI.cpp
  CrazyCanvas/Source/GUI/MultiplayerGUI.cpp
  CrazyCanvas/Source/States/MultiplayerState.cpp
Labels: Fix, Networking

#360 Change Paint depending on the server's projectile collision point
  Assets/Shaders/Geometry/GeomMeshPaint.frag
  Assets/Shaders/MeshPainting/Unwrap.frag
  CrazyCanvas/Include/EventHandlers/MeshPaintHandler.h
  CrazyCanvas/Include/Multiplayer/Packet/PacketProjectileHit.h
  CrazyCanvas/Include/Multiplayer/Packet/PacketType.h
  CrazyCanvas/Include/States/ServerState.h
  CrazyCanvas/Source/ECS/Systems/Player/WeaponSystem.cpp
  CrazyCanvas/Source/ECS/Systems/Player/WeaponSystemServer.cpp
  CrazyCanvas/Source/EventHandlers/MeshPaintHandler.cpp
  CrazyCanvas/Source/Multiplayer/PacketType.cpp
  CrazyCanvas/Source/States/ServerState.cpp
  LambdaEngine/Include/Rendering/PaintMaskRenderer.h
  LambdaEngine/Source/Rendering/PaintMaskRenderer.cpp
Labels: Fix, Networking

#366 Remove gui test
  CrazyCanvas/Include/GUI/GUITest.h
  CrazyCanvas/Include/States/SandboxState.h
  CrazyCanvas/Source/GUI/GUITest.cpp
  CrazyCanvas/Source/States/SandboxState.cpp
Labels: Clean Up

#367 Moved ClientSystem & ServerSystem Initialization
  CrazyCanvas/Source/CrazyCanvas.cpp
  LambdaEngine/Include/Rendering/ParticleManager.h
  LambdaEngine/Source/Game/ECS/Systems/Rendering/RenderSystem.cpp
  LambdaEngine/Source/Rendering/ParticleManager.cpp
Labels: Fix

#368 Fixed mesh painting in singleplayer and added some nice things to have
  Assets/Shaders/Defines.glsl
  Assets/Shaders/MeshPainting/Unwrap.frag
  CrazyCanvas/Source/EventHandlers/MeshPaintHandler.cpp
  LambdaEngine/Include/Rendering/PaintMaskRenderer.h
  LambdaEngine/Source/Rendering/PaintMaskRenderer.cpp
  premake5.lua
Labels: Clean Up, Fix

#370 Fix Particles Spawning Problematik
  CrazyCanvas/Source/World/LevelObjectCreator.cpp
  LambdaEngine/Source/Game/ECS/Systems/Physics/PhysicsSystem.cpp
Labels: Fix

#365 Pbr players
  Assets/RenderGraphs/RT_DEFERRED_PBR.lrg
  Assets/RenderGraphs/RT_DEFERRED_PBR_MESH.lrg
  Assets/Shaders/Geometry/GeomMeshPaint.frag
  Assets/Shaders/MeshPaintHelper.glsl
  Assets/Shaders/Noise.glsl
  Assets/Shaders/Paint.glsl
  Assets/Shaders/Players/Players.frag
  Assets/World/LevelModules/test.glb
  CrazyCanvas/Source/RenderStages/PlayerRenderer.cpp
Labels: Game, Rendering

#372 Fixed Dead lock in NetworkDiscovery
  LambdaEngine/Include/Networking/API/UDP/NetworkDiscovery.h
  LambdaEngine/Source/Networking/API/UDP/NetworkDiscovery.cpp
Labels: Fix, Networking

#374 Fixed bugs related to the client and the server
  CrazyCanvas/Include/GUI/LobbyGUI.h
  CrazyCanvas/Include/GUI/MultiplayerGUI.h
  CrazyCanvas/Include/Lobby/IPlayerManager.h
  CrazyCanvas/Include/Lobby/PlayerManagerBase.h
  CrazyCanvas/Include/Lobby/PlayerManagerClient.h
  CrazyCanvas/Include/Lobby/PlayerManagerServer.h
  CrazyCanvas/Include/Multiplayer/Packet/PacketGameSettings.h
  CrazyCanvas/Include/Multiplayer/Packet/PacketJoin.h
  CrazyCanvas/Include/Multiplayer/ServerHelper.h
  CrazyCanvas/Include/States/LobbyState.h
  CrazyCanvas/Include/States/PlaySessionState.h
  CrazyCanvas/Include/States/ServerState.h
  CrazyCanvas/Saved_Servers.json
  CrazyCanvas/Source/GUI/LobbyGUI.cpp
  CrazyCanvas/Source/GUI/MultiplayerGUI.cpp
  CrazyCanvas/Source/GUI/ServerInfo.cpp
  CrazyCanvas/Source/Lobby/PlayerManagerBase.cpp
  CrazyCanvas/Source/Lobby/PlayerManagerServer.cpp
  CrazyCanvas/Source/States/LobbyState.cpp
  CrazyCanvas/Source/States/PlaySessionState.cpp
  CrazyCanvas/Source/States/ServerState.cpp
  CrazyCanvas/engine_config_client.json
  LambdaEngine/Include/Application/API/Events/NetworkEvents.h
  LambdaEngine/Include/Game/Multiplayer/Client/ClientSystem.h
  LambdaEngine/Include/Game/Multiplayer/Server/ClientRemoteSystem.h
  LambdaEngine/Include/Networking/API/ClientBase.h
  LambdaEngine/Include/Networking/API/IClientHandler.h
  LambdaEngine/Include/Networking/API/IClientRemoteHandler.h
  LambdaEngine/Include/Networking/API/PacketManagerBase.h
  LambdaEngine/Include/Networking/API/UDP/NetworkDiscovery.h
  LambdaEngine/Source/Game/Multiplayer/Client/ClientSystem.cpp
  LambdaEngine/Source/Game/Multiplayer/Server/ClientRemoteSystem.cpp
  LambdaEngine/Source/Networking/API/ClientBase.cpp
  LambdaEngine/Source/Networking/API/ClientRemoteBase.cpp
  LambdaEngine/Source/Networking/API/PacketManagerBase.cpp
  LambdaEngine/Source/Networking/API/UDP/NetworkDiscovery.cpp
Labels: Fix, GUI, Multiplayer, Networking

#375 Match over logic
  Assets/NoesisGUI/Textures/LifeContainer.png
  Assets/NoesisGUI/Textures/LifeContainerFiller.png
  Assets/NoesisGUI/Textures/ScoreBoard.png
  Assets/NoesisGUI/Xaml/GameOverGUI.xaml
  Assets/NoesisGUI/Xaml/HUD.xaml
  Assets/NoesisGUI/Xaml/Multiplayer.xaml
  Assets/Sounds/2currency.wav
  CrazyCanvas/Include/ECS/Systems/GUI/HUDSystem.h
  CrazyCanvas/Include/Events/MatchEvents.h
  CrazyCanvas/Include/GUI/GameOverGUI.h
  CrazyCanvas/Include/GUI/HUDGUI.h
  CrazyCanvas/Include/Match/MatchBase.h
  CrazyCanvas/Include/Match/MatchClient.h
  CrazyCanvas/Include/World/Player/PlayerActionSystem.h
  CrazyCanvas/Saved_Servers.json
  CrazyCanvas/Source/CrazyCanvas.cpp
  CrazyCanvas/Source/ECS/Systems/GUI/HUDSystem.cpp
  CrazyCanvas/Source/ECS/Systems/Player/WeaponSystem.cpp
  CrazyCanvas/Source/GUI/GameOverGUI.cpp
  CrazyCanvas/Source/GUI/HUDGUI.cpp
  CrazyCanvas/Source/Match/MatchClient.cpp
  CrazyCanvas/Source/Match/MatchServer.cpp
  CrazyCanvas/Source/World/Player/PlayerActionSystem.cpp
Labels: GUI

#377 Scoreboard
  Assets/NoesisGUI/Xaml/CountdownGUI.xaml
  Assets/NoesisGUI/Xaml/HUD.xaml
  Assets/NoesisGUI/Xaml/MainMenu.xaml
  CrazyCanvas/Include/ECS/Systems/GUI/HUDSystem.h
  CrazyCanvas/Include/GUI/GUIHelpers.h
  CrazyCanvas/Include/GUI/HUDGUI.h
  CrazyCanvas/Source/ECS/Systems/GUI/HUDSystem.cpp
  CrazyCanvas/Source/GUI/HUDGUI.cpp
  CrazyCanvas/Source/GUI/MainMenuGUI.cpp
  CrazyCanvas/key_bindings.json
  LambdaEngine/Include/Input/API/ActionCodes.h
  LambdaEngine/Source/Input/API/InputActionSystem.cpp
Labels: GUI, Game, Networking

#382 BugFix in HealthSystem
  Assets/NoesisGUI/Xaml/DamageIndicatorGUI.xaml
  Assets/NoesisGUI/Xaml/EnemyHitIndicatorGUI.xaml
  CrazyCanvas/Include/GUI/HUDGUI.h
  CrazyCanvas/Source/ECS/Systems/Player/HealthSystemClient.cpp
  CrazyCanvas/Source/GUI/HUDGUI.cpp
Labels: Fix

#387 Networking lobby
  CrazyCanvas/Include/ECS/Systems/GUI/HUDSystem.h
  CrazyCanvas/Include/Events/PlayerEvents.h
  CrazyCanvas/Include/GUI/LobbyGUI.h
  CrazyCanvas/Include/Lobby/PlayerManagerServer.h
  CrazyCanvas/Include/Match/Match.h
  CrazyCanvas/Include/Match/MatchBase.h
  CrazyCanvas/Include/Match/MatchServer.h
  CrazyCanvas/Include/Multiplayer/Packet/PacketHealthChanged.h
  CrazyCanvas/Include/Multiplayer/Packet/PacketPlayerAliveChanged.h
  CrazyCanvas/Include/States/PlaySessionState.h
  CrazyCanvas/Include/States/ServerState.h
  CrazyCanvas/Source/ECS/Systems/GUI/HUDSystem.cpp
  CrazyCanvas/Source/ECS/Systems/Player/HealthSystemClient.cpp
  CrazyCanvas/Source/ECS/Systems/Player/HealthSystemServer.cpp
  CrazyCanvas/Source/GUI/LobbyGUI.cpp
  CrazyCanvas/Source/GUI/MainMenuGUI.cpp
  CrazyCanvas/Source/Lobby/PlayerManagerClient.cpp
  CrazyCanvas/Source/Lobby/PlayerManagerServer.cpp
  CrazyCanvas/Source/Match/Match.cpp
  CrazyCanvas/Source/Match/MatchServer.cpp
  CrazyCanvas/Source/States/LobbyState.cpp
  CrazyCanvas/Source/States/PlaySessionState.cpp
  CrazyCanvas/Source/States/ServerState.cpp
Labels: Fix, Game, Multiplayer

#386 Enemy Weapons are invisible
  CrazyCanvas/Source/World/LevelObjectCreator.cpp
  LambdaEngine/Include/Game/ECS/Components/Player/PlayerRelatedComponent.h
  LambdaEngine/Source/Rendering/EntityMaskManager.cpp
Labels: Game, Rendering

#389 Fixed Lobby settings and removed Unused state
  CrazyCanvas/Include/States/RenderGraphEditorState.h
  CrazyCanvas/Source/GUI/LobbyGUI.cpp
Labels: Clean Up, Fix

#392 Fix: server name appears for host
  CrazyCanvas/Include/GUI/LobbyGUI.h
  CrazyCanvas/Source/GUI/LobbyGUI.cpp
Labels: Fix, GUI

#397 All players have the same color
  CrazyCanvas/Source/Teams/TeamHelper.cpp
Labels: Game, Multiplayer

#398 Fixed TextBox limit of 24 characters
  CrazyCanvas/Include/GUI/LobbyGUI.h
  CrazyCanvas/Saved_Servers.json
  CrazyCanvas/Source/GUI/LobbyGUI.cpp
  CrazyCanvas/Source/GUI/MultiplayerGUI.cpp
  CrazyCanvas/Source/States/ServerState.cpp
Labels: Fix, GUI, Multiplayer

#399 Player Weapon rendered correctly
  CrazyCanvas/Include/RenderStages/PlayerRenderer.h
  CrazyCanvas/Source/RenderStages/PlayerRenderer.cpp
Labels: Fix, Rendering

#400 Fixed PlayerRegister on Client side
  CrazyCanvas/Source/Match/MatchClient.cpp
Labels: Fix, Multiplayer

#405 Fixed Unloading Bug
  LambdaEngine/Source/Resources/ResourceManager.cpp
Labels: Fix

#407 The team value of a player is now set when joining the lobby
  CrazyCanvas/Include/GUI/LobbyGUI.h
  CrazyCanvas/Include/Lobby/PlayerManagerBase.h
  CrazyCanvas/Include/Lobby/PlayerManagerServer.h
  CrazyCanvas/Include/Match/MatchServer.h
  CrazyCanvas/Include/Multiplayer/Packet/PacketCreateLevelObject.h
  CrazyCanvas/Include/States/LobbyState.h
  CrazyCanvas/Include/World/LevelObjectCreator.h
  CrazyCanvas/Source/GUI/LobbyGUI.cpp
  CrazyCanvas/Source/Lobby/PlayerManagerBase.cpp
  CrazyCanvas/Source/Lobby/PlayerManagerServer.cpp
  CrazyCanvas/Source/Match/MatchClient.cpp
  CrazyCanvas/Source/Match/MatchServer.cpp
  CrazyCanvas/Source/Multiplayer/SingleplayerInitializer.cpp
  CrazyCanvas/Source/States/BenchmarkState.cpp
  CrazyCanvas/Source/States/LobbyState.cpp
  CrazyCanvas/Source/World/LevelObjectCreator.cpp
  CrazyCanvas/engine_config_crazycanvas.json
Labels: Fix, Game, Multiplayer

#409 Fixed Player Animation System on Server
  CrazyCanvas/Source/ECS/Systems/Player/PlayerAnimationSystem.cpp
  CrazyCanvas/Source/ECS/Systems/Player/WeaponSystemClient.cpp
Labels: Fix

#410 The Lobby chat now use Colors from the team
  Assets/NoesisGUI/Xaml/Lobby.xaml
  CrazyCanvas/Include/Events/MatchEvents.h
  CrazyCanvas/Include/GUI/LobbyGUI.h
  CrazyCanvas/Source/ECS/Systems/Match/ServerFlagSystem.cpp
  CrazyCanvas/Source/GUI/LobbyGUI.cpp
  CrazyCanvas/Source/Lobby/PlayerManagerClient.cpp
  CrazyCanvas/Source/Match/MatchServer.cpp
Labels: Fix, GUI, Game, Multiplayer

#413 Fixed Scroll Problem
  LambdaEngine/Source/Application/Win32/Win32Application.cpp
  LambdaEngine/Source/GUI/Core/GUIApplication.cpp
Labels: Fix

#414 Volume fix
  Assets/NoesisGUI/Xaml/HUD.xaml
  Assets/NoesisGUI/Xaml/MainMenu.xaml
  Assets/Textures/MeshPainting/brush-sdf-3.png
  CrazyCanvas/Include/GUI/HUDGUI.h
  CrazyCanvas/Include/GUI/MainMenuGUI.h
  CrazyCanvas/Source/GUI/HUDGUI.cpp
  CrazyCanvas/Source/GUI/MainMenuGUI.cpp
Labels: Fix, GUI

#415 Implement jump
  CrazyCanvas/Include/Multiplayer/Packet/PacketPlayerAction.h
  CrazyCanvas/Include/World/Player/PlayerActionSystem.h
  CrazyCanvas/Include/World/Player/PlayerGameState.h
  CrazyCanvas/Source/World/Player/CharacterControllerHelper.cpp
  CrazyCanvas/Source/World/Player/Client/PlayerLocalSystem.cpp
  CrazyCanvas/Source/World/Player/PlayerActionSystem.cpp
  CrazyCanvas/Source/World/Player/Server/PlayerRemoteSystem.cpp
Labels: Game, Multiplayer, Physics

#418 Add icon
  Assets/CrazyCanvas.ico
  Assets/guy.ico
  LambdaEngine/Source/Application/API/CommonApplication.cpp
  LambdaEngine/Source/Application/Win32/Win32Application.cpp
Labels: Fix, GUI

#419 Fluid movement
  Assets/NoesisGUI/Xaml/HUD.xaml
  Assets/NoesisGUI/Xaml/MainMenu.xaml
  Assets/Sounds/Player/step.wav
  Assets/Sounds/Player/stepOrig.wav
  CrazyCanvas/Include/ECS/Components/Multiplayer/PacketComponent.h
  CrazyCanvas/Include/ECS/Systems/Multiplayer/Client/ReplayBaseSystem.h
  CrazyCanvas/Include/ECS/Systems/Player/WeaponSystem.h
  CrazyCanvas/Include/ECS/Systems/Player/WeaponSystemClient.h
  CrazyCanvas/Include/Events/GameplayEvents.h
  CrazyCanvas/Include/Multiplayer/Packet/PacketPlayerAction.h
  CrazyCanvas/Include/Multiplayer/Packet/PacketPlayerActionResponse.h
  CrazyCanvas/Include/Teams/TeamHelper.h
  CrazyCanvas/Include/World/LevelObjectCreator.h
  CrazyCanvas/Include/World/Player/CharacterControllerHelper.h
  CrazyCanvas/Include/World/Player/Client/PlayerLocalSystem.h
  CrazyCanvas/Include/World/Player/Client/PlayerSoundHelper.h
  CrazyCanvas/Include/World/Player/PlayerActionSystem.h
  CrazyCanvas/Include/World/Player/PlayerGameState.h
  CrazyCanvas/Include/World/Player/PlayerSettings.h
  CrazyCanvas/Source/ECS/Systems/Multiplayer/Client/ReplayManagerSystem.cpp
  CrazyCanvas/Source/ECS/Systems/Multiplayer/PacketTranscoderSystem.cpp
  CrazyCanvas/Source/ECS/Systems/Player/BenchmarkSystem.cpp
  CrazyCanvas/Source/ECS/Systems/Player/WeaponSystem.cpp
  CrazyCanvas/Source/ECS/Systems/Player/WeaponSystemClient.cpp
  CrazyCanvas/Source/ECS/Systems/Player/WeaponSystemServer.cpp
  CrazyCanvas/Source/GUI/HUDGUI.cpp
  CrazyCanvas/Source/GUI/MainMenuGUI.cpp
  CrazyCanvas/Source/Match/MatchClient.cpp
  CrazyCanvas/Source/States/SandboxState.cpp
  CrazyCanvas/Source/Teams/TeamHelper.cpp
  CrazyCanvas/Source/World/LevelObjectCreator.cpp
  CrazyCanvas/Source/World/Player/CharacterControllerHelper.cpp
  CrazyCanvas/Source/World/Player/Client/PlayerForeignSystem.cpp
  CrazyCanvas/Source/World/Player/Client/PlayerLocalSystem.cpp
  CrazyCanvas/Source/World/Player/Client/PlayerSoundHelper.cpp
  CrazyCanvas/Source/World/Player/PlayerActionSystem.cpp
  CrazyCanvas/Source/World/Player/Server/PlayerRemoteSystem.cpp
  CrazyCanvas/engine_config_crazycanvas.json
  CrazyCanvas/key_bindings.json
  LambdaEngine/Include/Audio/API/ISoundInstance3D.h
  LambdaEngine/Include/Game/ECS/Components/Audio/AudibleComponent.h
  LambdaEngine/Include/Game/ECS/Systems/Audio/AudioSystem.h
  LambdaEngine/Include/Input/API/ActionCodes.h
  LambdaEngine/Source/Engine/EngineLoop.cpp
  LambdaEngine/Source/Game/ECS/Components/Rendering/CameraComponent.cpp
  LambdaEngine/Source/Game/ECS/Systems/Audio/AudioSystem.cpp
  LambdaEngine/Source/Input/API/InputActionSystem.cpp
Labels: Audio, Clean Up, Game

#422 Fix client mask not clearing when shooting and crash when starting sandbox
  CrazyCanvas/Include/EventHandlers/MeshPaintHandler.h
  CrazyCanvas/Include/RenderStages/PlayerRenderer.h
  CrazyCanvas/Source/EventHandlers/MeshPaintHandler.cpp
  CrazyCanvas/Source/RenderStages/PlayerRenderer.cpp
Labels: Fix

#423 Fixed Render Stages sleeping in Benchmark
  CrazyCanvas/Include/GUI/MainMenuGUI.h
  CrazyCanvas/Source/GUI/MainMenuGUI.cpp
  CrazyCanvas/Source/States/BenchmarkState.cpp
Labels: Fix, Rendering

#426 Can not paint on yourself or others in your team
  Assets/Shaders/MeshPainting/Unwrap.frag
  Assets/Shaders/MeshPainting/Unwrap.vert
  CrazyCanvas/Include/EventHandlers/MeshPaintHandler.h
  CrazyCanvas/Include/Physics/PhysicsEvents.h
  CrazyCanvas/Include/RenderStages/PaintMaskRenderer.h
  CrazyCanvas/Source/CrazyCanvas.cpp
  CrazyCanvas/Source/EventHandlers/AudioEffectHandler.cpp
  CrazyCanvas/Source/EventHandlers/MeshPaintHandler.cpp
  CrazyCanvas/Source/RenderStages/PaintMaskRenderer.cpp
  LambdaEngine/Include/Rendering/CustomRenderer.h
  LambdaEngine/Source/Game/ECS/Systems/Rendering/RenderSystem.cpp
Labels: Clean Up, Fix

#428 Fixed GUI Resize Crash
  CrazyCanvas/Source/RenderStages/PlayerRenderer.cpp
  LambdaEngine/Include/GUI/Core/GUIRenderTarget.h
  LambdaEngine/Include/GUI/Core/GUIRenderer.h
  LambdaEngine/Include/Rendering/RenderGraph.h
  LambdaEngine/Source/GUI/Core/GUIRenderTarget.cpp
  LambdaEngine/Source/GUI/Core/GUIRenderer.cpp
Labels: Fix, GUI

#429 Remove player on disconnect
  CrazyCanvas/Include/Match/MatchServer.h
  CrazyCanvas/Source/Match/MatchServer.cpp
  CrazyCanvas/Source/World/LevelObjectCreator.cpp
Labels: Fix

#430 Step Cutoff, Music ingame & Resource Catalog
  CrazyCanvas/Include/CrazyCanvas.h
  CrazyCanvas/Include/GUI/MainMenuGUI.h
  CrazyCanvas/Include/Resources/ResourceCatalog.h
  CrazyCanvas/Include/States/MainMenuState.h
  CrazyCanvas/Include/World/LevelObjectCreator.h
  CrazyCanvas/Source/CrazyCanvas.cpp
  CrazyCanvas/Source/GUI/MainMenuGUI.cpp
  CrazyCanvas/Source/Resources/ResourceCatalog.cpp
  CrazyCanvas/Source/States/BenchmarkState.cpp
  CrazyCanvas/Source/States/LobbyState.cpp
  CrazyCanvas/Source/States/MainMenuState.cpp
  CrazyCanvas/Source/States/MultiplayerState.cpp
  CrazyCanvas/Source/States/PlaySessionState.cpp
  CrazyCanvas/Source/States/SandboxState.cpp
  CrazyCanvas/Source/World/LevelObjectCreator.cpp
  CrazyCanvas/Source/World/Player/Client/PlayerSoundHelper.cpp
  CrazyCanvas/engine_config_crazycanvas.json
  LambdaEngine/Include/Resources/ResourceManager.h
  LambdaEngine/Source/GUI/Core/GUIRenderer.cpp
Labels: Audio, Fix

#433 Mouse sensitivity, FOV & Minor Fixes
  Assets/NoesisGUI/Xaml/HUD.xaml
  Assets/NoesisGUI/Xaml/MainMenu.xaml
  CrazyCanvas/Include/GUI/HUDGUI.h
  CrazyCanvas/Include/GUI/MainMenuGUI.h
  CrazyCanvas/Include/World/Player/PlayerSettings.h
  CrazyCanvas/Source/GUI/HUDGUI.cpp
  CrazyCanvas/Source/GUI/MainMenuGUI.cpp
  CrazyCanvas/Source/World/Player/PlayerActionSystem.cpp
  CrazyCanvas/engine_config_crazycanvas.json
  CrazyCanvas/key_bindings.json
  LambdaEngine/Include/Game/ECS/Components/Rendering/CameraComponent.h
  LambdaEngine/Include/Game/ECS/Systems/CameraSystem.h
  LambdaEngine/Include/Input/API/InputActionSystem.h
  LambdaEngine/Source/Audio/FMOD/MusicFMOD.cpp
  LambdaEngine/Source/Game/ECS/Systems/CameraSystem.cpp
  LambdaEngine/Source/Input/API/InputActionSystem.cpp
Labels: Fix, Game

#434 Render System Debugging
  LambdaEngine/Include/Game/ECS/Systems/Rendering/RenderSystem.h
  LambdaEngine/Source/Game/ECS/Systems/Rendering/RenderSystem.cpp
Labels: Rendering

#437 Fixed Jetpack
  LambdaEngine/Include/Game/ECS/Systems/Physics/PhysicsSystem.h
  LambdaEngine/Include/Physics/PhysX/QueryFilterCallback.h
  LambdaEngine/Source/Game/ECS/Systems/Physics/PhysicsSystem.cpp
Labels: Fix, Physics

#445 [HOTFIX] Fixed mesh shader disabled
  Assets/RenderGraphs/RT_DEFERRED_PBR.lrg
  CrazyCanvas/Source/GUI/MainMenuGUI.cpp
  CrazyCanvas/Source/States/SandboxState.cpp
Labels: Fix

#444 Gui cleanup & PromptGUI
  Assets/NoesisGUI/Textures/FlagScore.png
  Assets/NoesisGUI/Textures/ScoreBoard.png
  Assets/NoesisGUI/Xaml/EscapeMenuGUI.xaml
  Assets/NoesisGUI/Xaml/HUD.xaml
  Assets/NoesisGUI/Xaml/PromptGUI.xaml
  CrazyCanvas/Include/ECS/Systems/GUI/HUDSystem.h
  CrazyCanvas/Include/GUI/EscapeMenuGUI.h
  CrazyCanvas/Include/GUI/HUDGUI.h
  CrazyCanvas/Include/GUI/PromptGUI.h
  CrazyCanvas/Include/Multiplayer/Packet/PacketTeamScored.h
  CrazyCanvas/Saved_Servers.json
  CrazyCanvas/Source/CrazyCanvas.cpp
  CrazyCanvas/Source/ECS/Systems/GUI/HUDSystem.cpp
  CrazyCanvas/Source/ECS/Systems/Match/ServerFlagSystem.cpp
  CrazyCanvas/Source/GUI/EscapeMenuGUI.cpp
  CrazyCanvas/Source/GUI/HUDGUI.cpp
  CrazyCanvas/Source/GUI/PromptGUI.cpp
  CrazyCanvas/Source/Match/MatchClient.cpp
Labels: GUI, Game

#449 Kill feed
  Assets/NoesisGUI/Textures/HealthBorderNew.png
  Assets/NoesisGUI/Textures/HealthPlateNew.png
  Assets/NoesisGUI/Textures/HealthRectNew.png
  Assets/NoesisGUI/Textures/PaintDropWhite.png
  Assets/NoesisGUI/Textures/bar.png
  Assets/NoesisGUI/Textures/bar_background.png
  Assets/NoesisGUI/Textures/bar_contour.png
  Assets/NoesisGUI/Xaml/HUD.xaml
  Assets/NoesisGUI/Xaml/KillFeedGUI.xaml
  CrazyCanvas/Include/GUI/HUDGUI.h
  CrazyCanvas/Include/GUI/KillFeedGUI.h
  CrazyCanvas/Source/CrazyCanvas.cpp
  CrazyCanvas/Source/ECS/Systems/GUI/HUDSystem.cpp
  CrazyCanvas/Source/GUI/HUDGUI.cpp
  CrazyCanvas/Source/GUI/KillFeedGUI.cpp
Labels: GUI

#454 Gui polish
  Assets/NoesisGUI/Textures/Blue Splatt.png
  Assets/NoesisGUI/Textures/PaintDrop.png
  Assets/NoesisGUI/Textures/PaintIcon.png
  Assets/NoesisGUI/Textures/Red Splatt.png
  Assets/NoesisGUI/Textures/Roller.png
  Assets/NoesisGUI/Textures/ScoreHolder.png
  Assets/NoesisGUI/Textures/ScoreHolder2.png
  Assets/NoesisGUI/Textures/WaterDrop.png
  Assets/NoesisGUI/Xaml/HUD.xaml
  Assets/NoesisGUI/Xaml/PromptGUI.xaml
  Assets/NoesisGUI/Xaml/ScoreBoardGUI.xaml
  CrazyCanvas/Include/ECS/Systems/Camera/SpectateCameraSystem.h
  CrazyCanvas/Include/GUI/HUDGUI.h
  CrazyCanvas/Include/GUI/ScoreBoardGUI.h
  CrazyCanvas/Source/CrazyCanvas.cpp
  CrazyCanvas/Source/ECS/Systems/Camera/SpectateCameraSystem.cpp
  CrazyCanvas/Source/ECS/Systems/GUI/HUDSystem.cpp
  CrazyCanvas/Source/GUI/GameOverGUI.cpp
  CrazyCanvas/Source/GUI/HUDGUI.cpp
  CrazyCanvas/Source/GUI/ScoreBoardGUI.cpp
Labels: GUI, Multiplayer

#460 Fix Weapon Depth Stencil Crash
  Assets/RenderGraphs/RT_DEFERRED_PBR.lrg
  Assets/RenderGraphs/RT_DEFERRED_PBR_MESH.lrg
  CrazyCanvas/Include/RenderStages/FirstPersonWeaponRenderer.h
  CrazyCanvas/Source/RenderStages/FirstPersonWeaponRenderer.cpp
Labels: Fix, Rendering

#456 Log file names and line numbers
  CrazyCanvas/Source/States/SandboxState.cpp
  CrazyCanvas/Source/World/LevelManager.cpp
  CrazyCanvas/Source/World/LevelObjectCreator.cpp
  LambdaEngine/Include/Log/Log.h
  LambdaEngine/Include/Physics/PhysX/ErrorCallback.h
  LambdaEngine/Source/Application/API/Events/EventQueue.cpp
  LambdaEngine/Source/Application/Win32/Win32Application.cpp
  LambdaEngine/Source/Audio/FMOD/AudioDeviceFMOD.cpp
  LambdaEngine/Source/Audio/FMOD/AudioGeometryFMOD.cpp
  LambdaEngine/Source/Audio/FMOD/MusicFMOD.cpp
  LambdaEngine/Source/Audio/FMOD/ReverbSphereFMOD.cpp
  LambdaEngine/Source/Audio/FMOD/SoundEffect2DFMOD.cpp
  LambdaEngine/Source/Audio/FMOD/SoundEffect3DFMOD.cpp
  LambdaEngine/Source/Audio/FMOD/SoundInstance2DFMOD.cpp
  LambdaEngine/Source/Audio/FMOD/SoundInstance3DFMOD.cpp
  LambdaEngine/Source/Debug/CPUProfiler.cpp
  LambdaEngine/Source/Debug/GPUProfiler.cpp
  LambdaEngine/Source/GUI/Core/GUIApplication.cpp
  LambdaEngine/Source/Game/ECS/Systems/Physics/PhysicsSystem.cpp
  LambdaEngine/Source/Game/ECS/Systems/Rendering/RenderSystem.cpp
  LambdaEngine/Source/Log/Log.cpp
  LambdaEngine/Source/Networking/API/ClientBase.cpp
  LambdaEngine/Source/Networking/API/UDP/ClientNetworkDiscovery.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/AccelerationStructureVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/BufferVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/CommandAllocatorVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/CommandQueueVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/ComputePipelineStateVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/DescriptorHeapVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/DeviceAllocatorVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/FenceVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/FrameBufferCacheVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/GraphicsDeviceVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/GraphicsPipelineStateVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/PipelineLayoutVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/QueryHeapVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/RayTracingPipelineStateVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/RenderPassVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/SBTVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/SamplerVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/ShaderVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/SwapChainVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/TextureVK.cpp
  LambdaEngine/Source/Rendering/Core/Vulkan/TextureViewVK.cpp
  LambdaEngine/Source/Rendering/ImGuiRenderer.cpp
  LambdaEngine/Source/Rendering/ParticleCollider.cpp
  LambdaEngine/Source/Rendering/PipelineStateManager.cpp
  LambdaEngine/Source/Rendering/RenderGraph.cpp
  LambdaEngine/Source/Resources/ResourceLoader.cpp
  LambdaEngine/Source/Resources/ResourceManager.cpp
Labels: Clean Up

#466 Fix ImGui Crash
  LambdaEngine/Source/Rendering/ImGuiRenderer.cpp
Labels: Fix, Rendering

#467 Include indices in meshlet cache files
  Assets/Meshes/MeshletCache/Marching Cubes Common Mesh
  LambdaEngine/Source/Resources/ResourceLoader.cpp
Labels: Fix

#469 Fix first person weapon rendering on spectator view
  Assets/NoesisGUI/Xaml/HUD.xaml
  CrazyCanvas/Source/ECS/Systems/Camera/SpectateCameraSystem.cpp
Labels: Fix

#472 Fix Leave-Join Crash
  CrazyCanvas/Source/RenderStages/FirstPersonWeaponRenderer.cpp
Labels: Fix
